version: "3.8"
services:
  postgres:
    image: postgres
    platform: linux/arm64
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  scheduler:
    image: apache/airflow
    platform: linux/arm64
    entrypoint: ./scripts/entrypoint.sh
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
  webserver:
    image: apache/airflow
    platform: linux/arm64
    deploy:
      restart_policy:
        condition: on-failure
    command: webserver
    depends_on:
      - scheduler
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
